# 
# setup 
#

name: Build Base Development Image
on:
    workflow_dispatch:
    schedule:
     - cron: "0 0 * * */6"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            # - name: Set up QEMU
            #   uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Generate Image Metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/${{ github.repository_owner }}/alpine_dev
                tags: |
                    type=schedule,pattern={{date 'YYYYMMDD'}}
                    type=sha
                    type=raw,value=latest,enable={{is_default_branch}}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                target: build-deps
                file: container/Dockerfile.dcchain
                context: "container"
                push: ${{ github.event_name != 'pull_request' }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                # build-args:


