# 
# setup 
#

name: Toolchain Build
on:
    workflow_dispatch:
        inputs:
            docker_target: 
                type: choice
                description: 'Docker Target to Build'
                options:
                    - 'sh4-toolchain'
                    - 'arm-toolchain'
                    - 'gdb-build'
            dcchain_args:
                description: 'Arguments to pass to dcchain'
                required: true
            image:
                description: 'Name to apply to docker image'
                required: true
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            
            # - name: Set up QEMU
            #   uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Clone KOS
              run: |
                cd container
                git clone https://github.com/KallistiOS/KallistiOS KOS

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                target: ${{ inputs.docker_target }}
                file: container/Dockerfile.dcchain
                context: "container"
                push: true
                tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}
                build-args: ${{ inputs.dcchain_args }}


